name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend lint
        working-directory: ./frontend
        run: npm run lint || echo "No lint script defined"

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build || echo "No build script defined"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend lint
        working-directory: ./backend
        run: npm run lint || echo "No lint script defined"

      - name: Run backend test
        working-directory: ./backend
        run: npm test || echo "No test script defined"
